# Generated by Django 5.1.6 on 2025-03-11 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', 'Only alphanumeric characters allowed.')])),
                ('type', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z ]+$', 'Only alphabets allowed.')])),
                ('date', models.DateField()),
                ('time_of_produce', models.TimeField()),
                ('tonnage_in_kgs', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('cost_per_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('total_cost', models.PositiveIntegerField(editable=False)),
                ('dealer_name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[a-zA-Z0-9 ]+$', 'Only alphanumeric characters allowed.')])),
                ('contact', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('price_to_sell', models.PositiveIntegerField()),
            ],
        ),
    ]
