# Generated by Django 5.1.6 on 2025-03-16 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='time_of_produce',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produce',
            name='tonnage_in_kgs',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
