# Generated by Django 5.1.6 on 2025-03-16 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0002_alter_produce_date_alter_produce_time_of_produce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='produce',
            name='time_of_produce',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
