# Generated by Django 5.1.6 on 2025-04-02 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0003_alter_produce_date_alter_produce_time_of_produce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="produce",
            name="name",
            field=models.CharField(
                choices=[
                    ("maize", "Maize"),
                    ("beans", "Beans"),
                    ("rice", "Rice"),
                    ("cowpeas", "Cowpeas"),
                    ("g-nuts", "Groundnuts"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="time_of_produce",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="produce",
            name="tonnage_in_kgs",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(100)]
            ),
        ),
        migrations.AlterField(
            model_name="produce",
            name="type",
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
