# Generated by Django 5.0.7 on 2025-04-03 18:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0004_alter_produce_date_alter_produce_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produce",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="produce",
            name="time_of_produce",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Selling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tonnage_in_kgs",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "amount_paid",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinLengthValidator(5)]
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                (
                    "sales_agent_name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(2)],
                    ),
                ),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "produce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kglapp.produce"
                    ),
                ),
            ],
        ),
    ]
