# Generated by Django 5.0.7 on 2025-04-03 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kglapp", "0005_alter_produce_date_alter_produce_time_of_produce_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selling",
            name="amount_paid",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinLengthValidator(1000)]
            ),
        ),
    ]
