# Generated by Django 5.0.3 on 2025-04-04 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0006_alter_selling_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='amount_paid',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
