# Generated by Django 5.0.3 on 2025-04-04 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kglapp', '0007_alter_selling_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling',
            name='date_time',
        ),
        migrations.AddField(
            model_name='selling',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
